openapi: 3.1.0
info:
  title: event-app-api
  version: 1.0.0
components:
  schemas:
    Message:
      type: object
      properties:
        message: 
          type: string
        timestamp: 
          type: string
    UsersPostBody:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        pwdhash:
          type: string
    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        pwdhash:
          type: string
        createdAt: 
          type: string

paths:
  /users/:
    post:
      deprecated: false
      description: Creates new user
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsersPostBody"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/User"
        "400":
          description: Missing fields
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "409":
          description: Username or Email already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"

